# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('nearest_railway_station', models.CharField(max_length=100)),
                ('number_of_members', models.IntegerField()),
                ('price_negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('preferred_guests', models.CharField(choices=[(1, 'Employee'), (1, 'Student')], max_length=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
