# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180310_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='contact',
            field=models.CharField(default='(91', max_length=10),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house_type',
            field=models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK+')], default='1 BHK', max_length=10),
        ),
        migrations.AlterField(
            model_name='flat',
            name='preferred_guests',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student')], default='Student', max_length=10),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
