# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180311_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='contact',
            field=models.CharField(default='91+', max_length=10),
        ),
    ]
